#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DOMAIN="${DEPLOY_DOMAIN:-apartments-demo.kynetropo.com}"
SERVER_DIR="${SERVER_DIR:-$ROOT_DIR/$DEPLOY_DOMAIN}"
PUBLIC_HTML_DIR="$SERVER_DIR/public_html"
BACKEND_DIR="$SERVER_DIR/backend"
DATABASE_DIR="$SERVER_DIR/database"
API_BASE_URL="${VITE_API_BASE_URL:-/api}"
APP_URL="${APP_URL:-https://$DEPLOY_DOMAIN}"
CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS:-https://$DEPLOY_DOMAIN}"

DB_HOST="${DB_HOST:-REPLACE_WITH_HOSTINGER_MYSQL_HOST}"
DB_PORT="${DB_PORT:-3306}"
DB_DATABASE="${DB_DATABASE:-REPLACE_WITH_HOSTINGER_DATABASE_NAME}"
DB_USERNAME="${DB_USERNAME:-REPLACE_WITH_HOSTINGER_DATABASE_USER}"
DB_PASSWORD="${DB_PASSWORD:-REPLACE_WITH_HOSTINGER_DATABASE_PASSWORD}"

OTP_DRIVER="${OTP_DRIVER:-webhook}"
OTP_WEBHOOK_URL="${OTP_WEBHOOK_URL:-REPLACE_WITH_SMS_PROVIDER_WEBHOOK_URL}"
OTP_WEBHOOK_TOKEN="${OTP_WEBHOOK_TOKEN:-REPLACE_WITH_SMS_PROVIDER_TOKEN}"

case "$SERVER_DIR" in
  "$ROOT_DIR"/"$DEPLOY_DOMAIN"|"$ROOT_DIR"/"$DEPLOY_DOMAIN"/*) ;;
  *)
    echo "Refusing to deploy outside the local repo $DEPLOY_DOMAIN/ folder: $SERVER_DIR" >&2
    exit 1
    ;;
esac

need_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

random_hex() {
  php -r 'echo bin2hex(random_bytes((int) $argv[1]));' "$1"
}

clean_backend_runtime_files() {
  mkdir -p \
    "$BACKEND_DIR/storage/logs" \
    "$BACKEND_DIR/storage/rate-limit" \
    "$BACKEND_DIR/storage/backups" \
    "$BACKEND_DIR/storage/uploads"

  rm -f "$BACKEND_DIR/storage/database.sqlite"
  find "$BACKEND_DIR/storage/logs" -type f ! -name '.gitkeep' -delete
  find "$BACKEND_DIR/storage/rate-limit" -type f ! -name '.gitkeep' -delete
  find "$BACKEND_DIR/storage/backups" -type f ! -name '.gitkeep' -delete
  find "$BACKEND_DIR/storage/uploads" -type f ! -name '.gitkeep' ! -name '.htaccess' -delete

  touch \
    "$BACKEND_DIR/storage/logs/.gitkeep" \
    "$BACKEND_DIR/storage/rate-limit/.gitkeep" \
    "$BACKEND_DIR/storage/backups/.gitkeep"
}

write_backend_env() {
  if [ -f "$BACKEND_DIR/.env" ] && [ "${REGENERATE_ENV:-0}" != "1" ]; then
    echo "Keeping existing backend .env. Set REGENERATE_ENV=1 to create a new one."
    chmod 600 "$BACKEND_DIR/.env"
    return
  fi

  local jwt_access_secret="${JWT_ACCESS_SECRET:-$(random_hex 64)}"
  local jwt_refresh_secret="${JWT_REFRESH_SECRET:-$(random_hex 64)}"
  local seed_admin_password="${SEED_ADMIN_PASSWORD:-$(random_hex 16)}"
  local seed_security_password="${SEED_SECURITY_PASSWORD:-$(random_hex 16)}"
  local seed_tenant_password="${SEED_TENANT_PASSWORD:-$(random_hex 16)}"
  local gate_visitor_entry="${SEED_GATE_VISITOR_ENTRY_TOKEN:-$(random_hex 32)}"
  local gate_visitor_checkout="${SEED_GATE_VISITOR_CHECKOUT_TOKEN:-$(random_hex 32)}"
  local gate_vehicle_entry="${SEED_GATE_VEHICLE_ENTRY_TOKEN:-$(random_hex 32)}"
  local gate_vehicle_checkout="${SEED_GATE_VEHICLE_CHECKOUT_TOKEN:-$(random_hex 32)}"

  cat > "$BACKEND_DIR/.env" <<ENV
APP_NAME=OfficeGate API
APP_ENV=production
APP_DEBUG=false
APP_URL=$APP_URL
APP_TIMEZONE=Asia/Kolkata

CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
TRUSTED_PROXIES=

JWT_ACCESS_SECRET=$jwt_access_secret
JWT_REFRESH_SECRET=$jwt_refresh_secret
JWT_ACCESS_TTL_SECONDS=900
JWT_REFRESH_TTL_SECONDS=1209600

DB_DRIVER=mysql
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_DATABASE=$DB_DATABASE
DB_USERNAME=$DB_USERNAME
DB_PASSWORD=$DB_PASSWORD

SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@officegate.com}
SEED_ADMIN_PASSWORD=$seed_admin_password
SEED_SECURITY_EMAIL=${SEED_SECURITY_EMAIL:-security@officegate.com}
SEED_SECURITY_PASSWORD=$seed_security_password
SEED_TENANT_EMAIL=${SEED_TENANT_EMAIL:-tenant@officegate.com}
SEED_TENANT_PASSWORD=$seed_tenant_password

OTP_DRIVER=$OTP_DRIVER
OTP_TTL_SECONDS=300
OTP_WEBHOOK_URL=$OTP_WEBHOOK_URL
OTP_WEBHOOK_TOKEN=$OTP_WEBHOOK_TOKEN

SEED_GATE_VISITOR_ENTRY_TOKEN=$gate_visitor_entry
SEED_GATE_VISITOR_CHECKOUT_TOKEN=$gate_visitor_checkout
SEED_GATE_VEHICLE_ENTRY_TOKEN=$gate_vehicle_entry
SEED_GATE_VEHICLE_CHECKOUT_TOKEN=$gate_vehicle_checkout
ENV

  chmod 600 "$BACKEND_DIR/.env"
}

write_server_readme() {
  cat > "$SERVER_DIR/README.md" <<'MD'
# Local Domain Deploy Folder

This folder is generated by `./.deploy.sh` and mirrors the Hostinger upload layout.

Upload mapping:

- `apartments-demo.kynetropo.com/public_html/*` -> Hostinger `domains/apartments-demo.kynetropo.com/public_html/`
- `apartments-demo.kynetropo.com/backend/*` -> Hostinger `domains/apartments-demo.kynetropo.com/backend/`
- `apartments-demo.kynetropo.com/.htaccess` -> Hostinger `domains/apartments-demo.kynetropo.com/.htaccess`
- `apartments-demo.kynetropo.com/database/officegate_production.sql` -> import through hPanel/phpMyAdmin

The generated `apartments-demo.kynetropo.com/backend/.env` is ignored by Git. Update its DB and OTP provider values before production use. Re-running `./.deploy.sh` preserves an existing `.env`; use `REGENERATE_ENV=1 ./.deploy.sh` only when you intentionally want new secrets.

Do not upload `backend/` inside `public_html/`. If `public_html/backend/` already exists on Hostinger, delete it.

Do not upload local `.vscode/sftp.json`.
MD
}

write_root_protection_htaccess() {
  cat > "$SERVER_DIR/.htaccess" <<'HTACCESS'
Options -Indexes

<IfModule mod_rewrite.c>
  RewriteEngine On

  RewriteRule (^|/)\. - [F,L]

  # Protect the domain root if Hostinger is accidentally pointed above public_html.
  RewriteRule ^(backend|database|docs|deployment|frontend|node_modules|scratch|server)(/|$) - [F,L]
  RewriteRule (^|/)(\.env|.*\.env|.*\.log|.*\.sql|.*\.sqlite|.*\.db|.*\.md)$ - [F,L]
</IfModule>

<FilesMatch "(^\.|\.env|\.log|\.sql|\.sqlite|\.db|\.md)$">
  Require all denied
</FilesMatch>
HTACCESS
}

need_command npm
need_command php

mkdir -p "$PUBLIC_HTML_DIR" "$BACKEND_DIR" "$DATABASE_DIR"
write_server_readme
write_root_protection_htaccess

echo "Building frontend into $DEPLOY_DOMAIN/public_html ..."
if [ ! -d "$ROOT_DIR/frontend/node_modules" ]; then
  (cd "$ROOT_DIR/frontend" && npm ci)
fi
# Build with Vite's default outDir (frontend/dist) and copy into public_html.
# Vite 8 / rolldown on Windows (Git Bash) ignores the `--outDir` CLI flag, so the
# previous approach silently emitted into frontend/dist and left public_html empty.
# MSYS_NO_PATHCONV/MSYS2_ARG_CONV_EXCL stop Git Bash from rewriting a leading-slash
# value like "/api" into a Windows path, which would bake a broken API base in.
DIST_DIR="$ROOT_DIR/frontend/dist"
rm -rf "$DIST_DIR"
(cd "$ROOT_DIR/frontend" && MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*' VITE_API_BASE_URL="$API_BASE_URL" npm run build)

if [ ! -f "$DIST_DIR/index.html" ]; then
  echo "Frontend build failed: $DIST_DIR/index.html not found." >&2
  exit 1
fi

# Clear public_html (keep nothing stale) then copy the fresh build in.
find "$PUBLIC_HTML_DIR" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
cp -R "$DIST_DIR/." "$PUBLIC_HTML_DIR/"

echo "Adding Hostinger Apache/API bridge files ..."
mkdir -p "$PUBLIC_HTML_DIR/api"
cp "$ROOT_DIR/deployment/hostinger/public_html/.htaccess" "$PUBLIC_HTML_DIR/.htaccess"
cp "$ROOT_DIR/deployment/hostinger/public_html/api/index.php" "$PUBLIC_HTML_DIR/api/index.php"

echo "Copying backend source into $DEPLOY_DOMAIN/backend ..."
copy_backend_source() {
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete \
      --exclude '.env' \
      --exclude 'vendor/' \
      --exclude '.phpunit.cache/' \
      "$ROOT_DIR/backend/" "$BACKEND_DIR/"
    return
  fi

  # rsync is not available (e.g. Git Bash on Windows). Fall back to a manual
  # mirror: wipe the destination except the preserved backend .env, then copy
  # everything from source except .env / vendor / .phpunit.cache.
  echo "rsync not found; using cp fallback."
  local preserved_env=""
  if [ -f "$BACKEND_DIR/.env" ]; then
    preserved_env="$(mktemp)"
    cp "$BACKEND_DIR/.env" "$preserved_env"
  fi

  find "$BACKEND_DIR" -mindepth 1 -maxdepth 1 ! -name '.env' -exec rm -rf {} +

  ( cd "$ROOT_DIR/backend" && \
    find . -mindepth 1 -maxdepth 1 \
      ! -name '.env' ! -name 'vendor' ! -name '.phpunit.cache' \
      -exec cp -R {} "$BACKEND_DIR/" \; )

  if [ -n "$preserved_env" ]; then
    cp "$preserved_env" "$BACKEND_DIR/.env"
    rm -f "$preserved_env"
  fi
}
copy_backend_source
clean_backend_runtime_files
write_backend_env

echo "Copying production database schema ..."
cp "$ROOT_DIR/database/officegate_production.sql" "$DATABASE_DIR/officegate_production.sql"

cat > "$SERVER_DIR/UPLOAD_MAP.txt" <<MAP
Upload map for Hostinger:

Target domain: $DEPLOY_DOMAIN

1. Upload $DEPLOY_DOMAIN/public_html/* to domains/$DEPLOY_DOMAIN/public_html/
2. Upload $DEPLOY_DOMAIN/backend/* to domains/$DEPLOY_DOMAIN/backend/
3. Upload $DEPLOY_DOMAIN/.htaccess to domains/$DEPLOY_DOMAIN/.htaccess as a root safety deny file.
4. Import $DEPLOY_DOMAIN/database/officegate_production.sql in hPanel/phpMyAdmin.
5. Review domains/$DEPLOY_DOMAIN/backend/.env and replace DB/SMS placeholders if they were not provided to .deploy.sh.

Important:
- Do not upload backend/ inside public_html/.
- If public_html/backend/ already exists on Hostinger, delete it.
- https://$DEPLOY_DOMAIN/backend/.env must return 403 or 404, never 200.
- Re-running .deploy.sh keeps the existing $DEPLOY_DOMAIN/backend/.env. Use REGENERATE_ENV=1 ./.deploy.sh only when you intentionally want new secrets.

Never upload local .vscode/sftp.json or backend/.env.
MAP

echo
echo "Server setup ready:"
echo "  Target domain:          $DEPLOY_DOMAIN"
echo "  Frontend static files: $PUBLIC_HTML_DIR"
echo "  Private PHP backend:   $BACKEND_DIR"
echo "  Backend env file:      $BACKEND_DIR/.env"
echo "  Database schema:       $DATABASE_DIR/officegate_production.sql"
echo
echo "Read: $SERVER_DIR/UPLOAD_MAP.txt"
